### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by charliex210** [bioinfocao/pysapc#2]
Hi,
I install pysapc by `pip` and error happen when I test the package:
`>>> from pysapc import tests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/public/home/lhlin/.conda/envs/rpy/lib/python3.6/site-packages/pysapc/__init__.py", line 1, in <module>
    from SparseAPCluster import SAP
ModuleNotFoundError: No module named 'SparseAPCluster'
`
Could you please fix the bug? Thx

**Comment by bioinfocao** [comment]
Previous version doesn't support python 3.
A new version supports python 3 has been uploaded.
Please download from github and re-install with python setup.py install.
